# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

# Fixing the relative import on python3. Issue: https://github.com/protocolbuffers/protobuf/pull/7470
from . import discount_calculator_pb2 as discount__calculator__pb2


class DiscountCalculatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CalculateDiscount = channel.unary_unary(
                '/DiscountCalculator/CalculateDiscount',
                request_serializer=discount__calculator__pb2.CalcDiscountRequest.SerializeToString,
                response_deserializer=discount__calculator__pb2.CalcDiscountReply.FromString,
                )


class DiscountCalculatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CalculateDiscount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DiscountCalculatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CalculateDiscount': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateDiscount,
                    request_deserializer=discount__calculator__pb2.CalcDiscountRequest.FromString,
                    response_serializer=discount__calculator__pb2.CalcDiscountReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DiscountCalculator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DiscountCalculator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CalculateDiscount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DiscountCalculator/CalculateDiscount',
            discount__calculator__pb2.CalcDiscountRequest.SerializeToString,
            discount__calculator__pb2.CalcDiscountReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
