# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: discount_calculator.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='discount_calculator.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19\x64iscount_calculator.proto\"9\n\x13\x43\x61lcDiscountRequest\x12\x11\n\tprodut_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\"0\n\x11\x43\x61lcDiscountReply\x12\x1b\n\x13\x63\x61lculated_discount\x18\x01 \x01(\t2U\n\x12\x44iscountCalculator\x12?\n\x11\x43\x61lculateDiscount\x12\x14.CalcDiscountRequest\x1a\x12.CalcDiscountReply\"\x00\x62\x06proto3'
)




_CALCDISCOUNTREQUEST = _descriptor.Descriptor(
  name='CalcDiscountRequest',
  full_name='CalcDiscountRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='produt_id', full_name='CalcDiscountRequest.produt_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='CalcDiscountRequest.user_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=86,
)


_CALCDISCOUNTREPLY = _descriptor.Descriptor(
  name='CalcDiscountReply',
  full_name='CalcDiscountReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='calculated_discount', full_name='CalcDiscountReply.calculated_discount', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=136,
)

DESCRIPTOR.message_types_by_name['CalcDiscountRequest'] = _CALCDISCOUNTREQUEST
DESCRIPTOR.message_types_by_name['CalcDiscountReply'] = _CALCDISCOUNTREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CalcDiscountRequest = _reflection.GeneratedProtocolMessageType('CalcDiscountRequest', (_message.Message,), {
  'DESCRIPTOR' : _CALCDISCOUNTREQUEST,
  '__module__' : 'discount_calculator_pb2'
  # @@protoc_insertion_point(class_scope:CalcDiscountRequest)
  })
_sym_db.RegisterMessage(CalcDiscountRequest)

CalcDiscountReply = _reflection.GeneratedProtocolMessageType('CalcDiscountReply', (_message.Message,), {
  'DESCRIPTOR' : _CALCDISCOUNTREPLY,
  '__module__' : 'discount_calculator_pb2'
  # @@protoc_insertion_point(class_scope:CalcDiscountReply)
  })
_sym_db.RegisterMessage(CalcDiscountReply)



_DISCOUNTCALCULATOR = _descriptor.ServiceDescriptor(
  name='DiscountCalculator',
  full_name='DiscountCalculator',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=138,
  serialized_end=223,
  methods=[
  _descriptor.MethodDescriptor(
    name='CalculateDiscount',
    full_name='DiscountCalculator.CalculateDiscount',
    index=0,
    containing_service=None,
    input_type=_CALCDISCOUNTREQUEST,
    output_type=_CALCDISCOUNTREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DISCOUNTCALCULATOR)

DESCRIPTOR.services_by_name['DiscountCalculator'] = _DISCOUNTCALCULATOR

# @@protoc_insertion_point(module_scope)
